# netlify.toml

# Basic build settings for your Create React App
# This tells Netlify how to build your project and where to find the output.
[build]
  # The command Netlify will execute to build your project.
  # "npm run build" triggers the "build" script in your package.json,
  # which then automatically runs your "postbuild" script (react-snap).
  command = "npm run build"

  # The directory that Netlify will deploy after the build process completes.
  # For Create React App, this is typically 'build'.
  publish = "build"

# Configuration for Netlify Build Plugins.
# This section tells Netlify to use the sitemap plugin.
[[plugins]]
  # The package name of the plugin to use.
  package = "@netlify/plugin-sitemap"

  # Inputs (configuration options) for the @netlify/plugin-sitemap.
  [plugins.inputs]
  # The directory containing your built and pre-rendered HTML files.
  # The sitemap plugin will scan this directory to find your pages.
  buildDir = "build"

  # Your website's base URL. This is critical as all URLs in the sitemap
  # must be full, absolute URLs.
  # Make sure to replace "https://www.myhscounselor.com" with your actual domain.
  baseUrl = "https://www.myhscounselor.com"

  # Optional: Default change frequency for pages if not explicitly set.
  # This provides a general hint to search engines about how often content on your site changes.
  defaultChangeFreq = "monthly"

  # Optional: Default priority for pages if not explicitly set.
  # This indicates the relative importance of pages to each other (0.0 to 1.0).
  defaultPriority = "0.7"

  # Optional: Specific rules for individual page paths.
  # Use this to set custom changeFreq and priority for your most important pages.
  # The 'lastmod' cannot be set here; the plugin derives it from the file modification times.
  routes = [
    { path = "/", changeFreq = "daily", priority = "1.0" },
    { path = "/college-guide", changeFreq = "weekly", priority = "0.9" },
    { path = "/trade", changeFreq = "weekly", priority = "0.9" },
    { path = "/quiz", priority = "0.8" },
    # Add other critical pages from your 'reactSnap.include' list here if you want
    # to assign them a specific changeFreq or priority different from the default.
  ]

