export const CAREER_STATS = {
  '15-1252': {
    salary: '$95,000',
    outlook: 'Much faster than average (22%)',
    education: 'Bachelor’s degree in Computer Science or related field',
    skills: ['Problem-solving', 'Coding (JavaScript, Python)', 'Team collaboration'],
    certifications: ['CompTIA, AWS Certified Developer'],
    environment: 'Office or hybrid tech setting with strong growth potential',
  },
  '17-1011': {
    salary: '$82,000',
    outlook: 'Average (1%)',
    education: 'Bachelor’s degree in Architecture',
    skills: ['Design thinking', 'AutoCAD/Revit', 'Visualization'],
    certifications: ['State Licensure (ARE)'],
    environment: 'Architecture firms, construction sites, or city planning offices',
  },
  '15-2051': {
    salary: '$108,000',
    outlook: 'Much faster than average (35%)',
    education: 'Bachelor’s or Master’s in Data Science, Statistics, or CS',
    skills: ['Data analysis', 'Python/R', 'Machine learning'],
    certifications: ['Google Data Analytics, Microsoft Certified: Data Scientist'],
    environment: 'Corporate offices, tech startups, or research settings',
  },
  '27-3043': {
    salary: '$73,000',
    outlook: 'Faster than average (8%)',
    education: 'Bachelor’s in English, Journalism, or Communications',
    skills: ['Writing', 'Editing', 'Storytelling'],
    certifications: ['None required; portfolio is key'],
    environment: 'Freelance, publishing, media, or creative agencies',
  },
  '21-1023': {
    salary: '$56,000',
    outlook: 'Faster than average (10%)',
    education: 'Master’s in Counseling or Psychology',
    skills: ['Empathy', 'Listening', 'Emotional intelligence'],
    certifications: ['Licensed Professional Counselor (LPC)'],
    environment: 'Private practice, clinics, or schools',
  },
  '27-1011': {
    salary: '$105,000',
    outlook: 'Slower than average (1%)',
    education: 'Bachelor’s in Art, Design, or Marketing',
    skills: ['Design', 'Team leadership', 'Creative direction'],
    certifications: ['None required, portfolio-driven'],
    environment: 'Advertising agencies, studios, or media companies',
  },
  '25-2021': {
    salary: '$61,000',
    outlook: 'Faster than average (4%)',
    education: 'Bachelor’s in Education + State Teaching Credential',
    skills: ['Communication', 'Classroom management', 'Creativity'],
    certifications: ['State Teacher Certification'],
    environment: 'Elementary schools (public or private)',
  },
  '25-4022': {
    salary: '$61,660',
    outlook: 'As fast as average (3%)',
    education: 'Master’s in Library and Information Science (MLIS)',
    skills: ['Organization', 'Information retrieval', 'Tech literacy'],
    certifications: ['State Licensure (varies)'],
    environment: 'Schools, universities, or public libraries',
  },
  '29-1141': {
    salary: '$81,220',
    outlook: 'Faster than average (6%)',
    education: 'Bachelor’s in Nursing (BSN) + RN license',
    skills: ['Patient care', 'Clinical skills', 'Critical thinking'],
    certifications: ['Registered Nurse (RN) License'],
    environment: 'Hospitals, clinics, or home care',
  },
  '41-4012': {
    salary: '$60,000',
    outlook: 'Average (4%)',
    education: 'High school diploma or Bachelor’s in Business/Sales',
    skills: ['Persuasion', 'CRM software', 'Networking'],
    certifications: ['Salesforce or other CRM tools (optional)'],
    environment: 'Corporate sales, retail, or B2B environments',
  },
  '29-2043': {
    salary: '$49,000',
    outlook: 'Faster than average (5%)',
    education: 'EMT certification or Associate’s degree in Paramedicine',
    skills: ['First aid', 'Decision-making', 'Emergency care'],
    certifications: ['NREMT Certification'],
    environment: 'Ambulance services, hospitals, or emergency departments',
  },
  '47-1011': {
    salary: '$75,000',
    outlook: 'Average (4%)',
    education: 'High school + apprenticeship or associate degree',
    skills: ['Project management', 'Blueprint reading', 'Construction codes'],
    certifications: ['OSHA Certification'],
    environment: 'Construction sites or contracting offices',
  },
  '17-2199': {
    salary: '$95,000',
    outlook: 'Faster than average (7%)',
    education: 'Bachelor’s in Engineering (various types)',
    skills: ['Math', 'CAD tools', 'Analytical thinking'],
    certifications: ['Professional Engineer (PE) License'],
    environment: 'Office/lab or fieldwork depending on specialty',
  },
  '15-2041': {
    salary: '$82,000',
    outlook: 'Much faster than average (30%)',
    education: 'Bachelor’s in Statistics, Math, or Data Analytics',
    skills: ['Statistical modeling', 'SQL', 'Data visualization'],
    certifications: ['Google Data Analytics, SAS, Tableau'],
    environment: 'Finance, healthcare, tech, or research sectors',
  },
  '19-3011': {
    salary: '$113,940',
    outlook: 'Average (6%)',
    education: 'Master’s or PhD in Economics',
    skills: ['Research', 'Modeling', 'Policy analysis'],
    certifications: ['None required'],
    environment: 'Government, academia, or private think tanks',
  },
  '11-1021': {
    salary: '$100,000',
    outlook: 'Faster than average (5%)',
    education: 'Bachelor’s in Business or related field',
    skills: ['Leadership', 'Budgeting', 'Communication'],
    certifications: ['PMP (Project Management Professional)'],
    environment: 'Corporate settings across industries',
  },
  '33-3051': {
    salary: '$70,000',
    outlook: 'Faster than average (7%)',
    education: 'High school diploma + Police Academy',
    skills: ['Decision-making', 'Law knowledge', 'Stamina'],
    certifications: ['POST Certification (varies by state)'],
    environment: 'Police departments, patrol routes, or investigations',
  },
  '11-9111': {
    salary: '$104,830',
    outlook: 'Faster than average (28%)',
    education: 'Bachelor’s or Master’s in Health Admin or Nursing',
    skills: ['Healthcare operations', 'Compliance', 'Leadership'],
    certifications: ['FACHE, CPHQ (optional but preferred)'],
    environment: 'Hospitals, clinics, or healthcare systems',
  },
  '29-2042': {
    salary: '$39,410',
    outlook: 'Much faster than average (11%)',
    education: 'Postsecondary non-degree award',
    skills: ['EMT skills', 'Calm under pressure', 'Physical fitness'],
    certifications: ['EMT-Basic Certification'],
    environment: 'Ambulance services, emergency departments, or rescue teams',
  },
  '27-2011': {
    salary: '$61,160',
    outlook: 'Average (4%)',
    education: 'No formal education needed; talent and experience preferred',
    skills: ['Performance', 'Improvisation', 'Audience engagement'],
    certifications: ['Acting workshops, drama school (optional)'],
    environment: 'Theaters, studios, or live event venues',
  },
  '35-1011': {
    salary: '$58,740',
    outlook: 'Average (5%)',
    education: 'High school diploma + culinary school (preferred)',
    skills: ['Culinary skills', 'Creativity', 'Kitchen management'],
    certifications: ['ServSafe Certification'],
    environment: 'Restaurants, hotels, or private catering',
  }
};
